import { createClient } from "@supabase/supabase-js";
import "./safety.mjs";

const required = ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY", "LEDGERLY_QA_USER_A_EMAIL", "LEDGERLY_QA_USER_A_PASSWORD", "LEDGERLY_QA_USER_B_EMAIL", "LEDGERLY_QA_USER_B_PASSWORD"];
for (const key of required) if (!process.env[key]) throw new Error(`Missing ${key}`);
const make = () => createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const n = (value) => Number(value || 0), same = (a, b) => Math.abs(n(a) - n(b)) < 0.000001;
const ok = (value, message) => { if (!value) throw new Error(`FAIL ${message}`); console.log(`PASS ${message}`); };
const login = async (client, email, password) => { const { error } = await client.auth.signInWithPassword({ email, password }); if (error) throw error; };

const a = make(), b = make(), anon = make();
await login(a, process.env.LEDGERLY_QA_USER_A_EMAIL, process.env.LEDGERLY_QA_USER_A_PASSWORD);
await login(b, process.env.LEDGERLY_QA_USER_B_EMAIL, process.env.LEDGERLY_QA_USER_B_PASSWORD);
const organization = async (client, slug) => { const { data, error } = await client.from("organizations").select("id").eq("slug", slug).single(); if (error) throw error; return data; };
const orgA = await organization(a, "ledgerly-qa-company-a"), orgB = await organization(b, "ledgerly-qa-company-b");
const account = async (client, org, key) => { const { data, error } = await client.from("accounts").select("id").eq("organization_id", org).eq("system_key", key).single(); if (error) throw error; return data.id; };
const vat = async (client, org) => { const { data, error } = await client.from("tax_rates").select("id").eq("organization_id", org).eq("code", "VAT5").single(); if (error) throw error; return data.id; };
const expenseAccount = await account(a, orgA.id, "office_expense"), bank = await account(a, orgA.id, "main_bank"), cash = await account(a, orgA.id, "cash_on_hand"), invalidAccount = await account(a, orgA.id, "sales_revenue"), vat5 = await vat(a, orgA.id);
const today = new Date().toISOString().slice(0, 10), run = `EXP-QA-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const branch = async (client, org) => { const { data, error } = await client.from("branches").select("id,name").eq("organization_id", org).eq("status", "active").limit(1).single(); if (error) throw error; return data; };
const activeBranch = await branch(a, orgA.id), foreignBranch = await branch(b, orgB.id);
const draftArgs = (overrides = {}) => ({ p_organization_id: orgA.id, p_expense_date: today, p_expense_account_id: expenseAccount, p_payment_account_id: bank, p_net_amount: 100, p_tax_rate_id: null, p_payee_name: run, p_reference: run, ...overrides });
const activeBranchDraft = await a.rpc("create_expense_draft", draftArgs({ p_branch_id: activeBranch.id, p_reference: `${run}-active-branch` })); if (activeBranchDraft.error) throw activeBranchDraft.error;
ok(!(await a.rpc("delete_expense_draft", { p_organization_id: orgA.id, p_expense_id: activeBranchDraft.data })).error, "Active organization branch accepted");
const inactiveBranch = await a.rpc("create_organization_branch", { p_organization_id: orgA.id, p_name: `${run} inactive branch` }); if (inactiveBranch.error) throw inactiveBranch.error;
const deactivate = await a.rpc("update_organization_branch", { p_organization_id: orgA.id, p_branch_id: inactiveBranch.data, p_name: `${run} inactive branch`, p_status: "inactive" }); if (deactivate.error) throw deactivate.error;
ok((await a.rpc("create_expense_draft", draftArgs({ p_branch_id: inactiveBranch.data, p_reference: `${run}-inactive-branch` }))).error, "Inactive branch denied");
ok((await a.rpc("create_expense_draft", draftArgs({ p_branch_id: foreignBranch.id, p_reference: `${run}-foreign-branch` }))).error, "Cross-tenant branch denied");
const draft = await a.rpc("create_expense_draft", draftArgs()); if (draft.error) throw draft.error; ok(draft.data, "Draft expense created");
const updated = await a.rpc("update_expense_draft", { ...draftArgs({ p_net_amount: 110, p_payment_account_id: cash }), p_expense_id: draft.data }); ok(!updated.error, "Draft expense updated");
const remove = await a.rpc("delete_expense_draft", { p_organization_id: orgA.id, p_expense_id: draft.data }); ok(!remove.error, "Separate draft expense deleted");
const noVat = await a.rpc("create_expense_draft", draftArgs({ p_reference: `${run}-no-vat` })); if (noVat.error) throw noVat.error;
const noVatPost = await a.rpc("post_expense", { p_organization_id: orgA.id, p_expense_id: noVat.data }); if (noVatPost.error) throw noVatPost.error;
const noVatRow = await a.from("expenses").select("status,expense_number,posted_journal_id,total_amount").eq("id", noVat.data).single(); if (noVatRow.error) throw noVatRow.error;
const noVatLines = await a.from("journal_lines").select("account_id,debit_amount,credit_amount").eq("journal_entry_id", noVatRow.data.posted_journal_id); if (noVatLines.error) throw noVatLines.error;
ok(noVatRow.data.status === "posted" && noVatRow.data.expense_number && same(noVatRow.data.total_amount, 100), "Expense without VAT posts and receives a number");
ok(same(noVatLines.data.find((x) => x.account_id === expenseAccount)?.debit_amount, 100) && same(noVatLines.data.find((x) => x.account_id === bank)?.credit_amount, 100), "Expense without VAT debits expense and credits bank");
const withVat = await a.rpc("create_expense_draft", draftArgs({ p_tax_rate_id: vat5, p_reference: `${run}-vat` })); if (withVat.error) throw withVat.error;
const vatPost = await a.rpc("post_expense", { p_organization_id: orgA.id, p_expense_id: withVat.data }); if (vatPost.error) throw vatPost.error;
const vatRow = await a.from("expenses").select("status,posted_journal_id,net_amount,tax_amount,total_amount").eq("id", withVat.data).single(); if (vatRow.error) throw vatRow.error;
const vatLines = await a.from("journal_lines").select("account_id,debit_amount,credit_amount").eq("journal_entry_id", vatRow.data.posted_journal_id); if (vatLines.error) throw vatLines.error;
const inputVat = await account(a, orgA.id, "input_vat");
ok(same(vatRow.data.net_amount, 100) && same(vatRow.data.tax_amount, 5) && same(vatRow.data.total_amount, 105), "Backend calculates VAT and total deterministically");
ok(same(vatLines.data.find((x) => x.account_id === expenseAccount)?.debit_amount, 100) && same(vatLines.data.find((x) => x.account_id === inputVat)?.debit_amount, 5) && same(vatLines.data.find((x) => x.account_id === bank)?.credit_amount, 105), "VAT expense debits expense/Input VAT and credits bank");
ok(same(vatLines.data.reduce((sum, row) => sum + n(row.debit_amount), 0), vatLines.data.reduce((sum, row) => sum + n(row.credit_amount), 0)), "Expense journal balances");
const replay = await a.rpc("post_expense", { p_organization_id: orgA.id, p_expense_id: withVat.data }); ok(!replay.error && replay.data.already_posted && replay.data.journal_id === vatRow.data.posted_journal_id, "Posting is idempotent");
ok((await a.rpc("update_expense_draft", { ...draftArgs(), p_expense_id: withVat.data })).error && (await a.rpc("delete_expense_draft", { p_organization_id: orgA.id, p_expense_id: withVat.data })).error, "Posted expense cannot be mutated through draft RPCs");
ok((await a.rpc("create_expense_draft", draftArgs({ p_expense_account_id: invalidAccount }))).error, "Invalid expense account denied");
ok((await a.rpc("create_expense_draft", draftArgs({ p_payment_account_id: invalidAccount }))).error, "Invalid Cash/Bank account denied");
ok((await b.rpc("post_expense", { p_organization_id: orgB.id, p_expense_id: withVat.data })).error, "Cross-tenant expense access denied");
ok((await anon.rpc("post_expense", { p_organization_id: orgA.id, p_expense_id: withVat.data })).error, "Anonymous expense posting denied");
const trial = await a.rpc("get_trial_balance", { p_organization_id: orgA.id }); if (trial.error) throw trial.error; ok(same((trial.data || []).reduce((sum, row) => sum + n(row.debit), 0), (trial.data || []).reduce((sum, row) => sum + n(row.credit), 0)), "Trial Balance remains balanced");
