"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createOperationalAccount, createTaxRate, initializeAccounting, saveAccount, saveAccountGroup, saveDocumentSequence, saveFinancialYear } from "@/app/actions/accounting";
import { useOrganizationContext } from "@/components/app-shell";
import { createClient } from "@/lib/supabase/client";

type Row = Record<string, unknown>;
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const date = new Date().getFullYear();

export function AccountingMasters({ page }: { page: "landing" | "accounts" | "groups" | "cash" | "bank" | "tax" | "years" | "numbering" | "opening" }) {
  const { organization } = useOrganizationContext(); const [rows, setRows] = useState<Row[]>([]); const [groups, setGroups] = useState<Row[]>([]); const [ready, setReady] = useState<boolean | null>(null); const [message, setMessage] = useState(""); const [search, setSearch] = useState("");
  const table = page === "landing" ? null : ({ accounts: "accounts", groups: "account_groups", cash: "cash_accounts", bank: "bank_accounts", tax: "tax_rates", years: "financial_years", numbering: "document_sequences", opening: "opening_balance_batches" } as const)[page];
  const load = async () => { const db = createClient(); const setup = await db.from("organization_settings").select("accounting_initialized_at").eq("organization_id", organization.id).maybeSingle(); setReady(Boolean(setup.data?.accounting_initialized_at)); if (table) { const result = await db.from(table).select(page === "accounts" ? "id,code,name,description,is_system,is_active,allow_manual_posting,cash_flow_category,account_group_id,account_groups(name,classification)" : page === "opening" ? "*,journal_entries(journal_number)" : "*").eq("organization_id", organization.id).order("created_at"); setRows((result.data ?? []) as unknown as Row[]); } const groupResult = await db.from("account_groups").select("id,code,name,classification,is_active").eq("organization_id", organization.id).eq("is_active", true).order("code"); setGroups((groupResult.data ?? []) as Row[]); };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [organization.id, page]);
  const run = async (work: Promise<{ ok?: true; error?: string }>) => { const result = await work; setMessage(result.error || "Saved."); if (!result.error) await load(); };
  if (ready === false) return <SetupCard run={run} />;
  if (ready === null) return <section className="panel"><p>Loading accounting setup…</p></section>;
  if (page === "landing") return <section className="panel accounting-landing"><div className="panel-head"><div><h2>Accounting masters</h2><p>Set up your accounts before you start posting transactions.</p></div></div><div className="master-grid">{[["Chart of Accounts","/accounting/chart-of-accounts","Your business ledger accounts"],["Account Groups","/accounting/account-groups","Keep accounts organized"],["Cash Accounts","/accounting/cash-accounts","Cash-on-hand locations"],["Bank Accounts","/accounting/bank-accounts","Linked bank ledgers"],["VAT / Tax Rates","/accounting/tax-rates","VAT codes and account mappings"],["Financial Years","/accounting/financial-years","Your reporting calendar"],["Document Numbering","/accounting/document-numbering","Invoice and receipt prefixes"]].map(([name, href, detail]) => <Link className="master-card" href={href} key={href}><strong>{name}</strong><span>{detail}</span><b>Open →</b></Link>)}</div></section>;
  if (page === "accounts") return <Accounts rows={rows} groups={groups} search={search} setSearch={setSearch} run={run} message={message} />;
  if (page === "groups") return <Groups rows={rows} run={run} message={message} />;
  if (page === "years") return <Years rows={rows} run={run} message={message} />;
  if (page === "numbering") return <Sequences rows={rows} run={run} message={message} />;
  if (page === "opening") return <Opening rows={rows} />;
  const titles = { cash: "Cash Accounts", bank: "Bank Accounts", tax: "VAT / Tax Rates" } as const;
  return <><section className="panel"><div className="panel-head"><div><h2>{titles[page as keyof typeof titles]}</h2><p>{page === "tax" ? "Starter tax codes are configurable and do not constitute tax advice." : "These operational records link to your Chart of Accounts."}</p></div></div><SimpleTable rows={rows} empty="No records have been created yet." /></section><OperationalForm kind={page as "cash" | "bank" | "tax"} run={run} message={message} /></>;
}

function SetupCard({ run }: { run: (work: Promise<{ ok?: true; error?: string }>) => void }) { const [name, setName] = useState(`FY ${date}`); const [start, setStart] = useState(`${date}-01-01`); const [end, setEnd] = useState(`${date}-12-31`); return <section className="panel setup-card"><h2>Set up accounting</h2><p>Create Ledgerly’s concise UAE SME starter chart, VAT starter codes, document numbering, and your first financial year. This is safe to retry and does not create transactions.</p><div className="form-grid"><label>Financial year name<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Start date<input type="date" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>End date<input type="date" value={end} onChange={(event) => setEnd(event.target.value)} /></label></div><button className="button" onClick={() => run(initializeAccounting({ financialYearName: name, startDate: start, endDate: end }))}>Set up accounting</button></section>; }
function Accounts({ rows, groups, search, setSearch, run, message }: { rows: Row[]; groups: Row[]; search: string; setSearch: (value: string) => void; run: (work: Promise<{ ok?: true; error?: string }>) => void; message: string }) { const [show, setShow] = useState(false); const [classification, setClassification] = useState("all"); const filtered = useMemo(() => rows.filter((row) => `${row.code} ${row.name}`.toLowerCase().includes(search.toLowerCase()) && (classification === "all" || (row.account_groups as { classification?: string } | null)?.classification === classification)), [rows, search, classification]); return <><section className="panel"><div className="panel-head"><div><h2>Chart of Accounts</h2><p>Financial statements derive balances and cash-flow treatment from this chart.</p></div><button className="button" onClick={() => setShow(true)}>Add account</button></div><div className="account-filters"><input placeholder="Search code or account" value={search} onChange={(event) => setSearch(event.target.value)} /><select value={classification} onChange={(event) => setClassification(event.target.value)}><option value="all">All classifications</option>{["asset", "liability", "equity", "income", "expense"].map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></div>{message && <p className="form-message">{message}</p>}<table className="data-table"><thead><tr><th>Code</th><th>Account Name</th><th>Group</th><th>Class</th><th>Cash Flow</th><th>Status</th></tr></thead><tbody>{filtered.map((row) => { const group = row.account_groups as { name?: string; classification?: string } | null; return <tr key={String(row.id)}><td>{String(row.code)}</td><td>{String(row.name)} {row.is_system ? <small>System</small> : null}</td><td>{group?.name}</td><td>{label(group?.classification || "")}</td><td>{row.cash_flow_category ? label(String(row.cash_flow_category)) : "Unclassified"}</td><td>{row.is_active ? "Active" : "Inactive"}</td></tr>; })}</tbody></table></section>{show && <AccountForm groups={groups} close={() => setShow(false)} run={run} />}</>; }
function AccountForm({ groups, close, run }: { groups: Row[]; close: () => void; run: (work: Promise<{ ok?: true; error?: string }>) => void }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(saveAccount({ code: String(form.get("code")), name: String(form.get("name")), groupId: String(form.get("group")), description: String(form.get("description")), manualPosting: form.get("manual") === "on", active: true, cashFlowCategory: String(form.get("cashFlow")) as "operating" | "investing" | "financing" })); close(); }; return <section className="panel form-panel"><form onSubmit={submit}><div className="panel-head"><h2>Add account</h2><button type="button" className="text-button" onClick={close}>Close</button></div><div className="form-grid"><label>Account code<input name="code" pattern="[0-9]{4}" required /></label><label>Account name<input name="name" required /></label><label>Account group<select name="group" required>{groups.map((group) => <option key={String(group.id)} value={String(group.id)}>{String(group.code)} · {String(group.name)}</option>)}</select></label><label>Cash-flow category<select name="cashFlow" defaultValue="operating" required><option value="operating">Operating</option><option value="investing">Investing</option><option value="financing">Financing</option></select></label><label>Description<input name="description" /></label><label className="check-label"><input type="checkbox" name="manual" defaultChecked /> Allow manual posting</label></div><button className="button">Save account</button></form></section>; }
function Groups({ rows, run, message }: { rows: Row[]; run: (work: Promise<{ ok?: true; error?: string }>) => void; message: string }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(saveAccountGroup({ code: String(form.get("code")), name: String(form.get("name")), classification: String(form.get("classification")) })); event.currentTarget.reset(); }; return <><section className="panel"><div className="panel-head"><div><h2>Account Groups</h2><p>System classifications stay protected.</p></div></div><SimpleTable rows={rows} /></section><section className="panel form-panel"><h2>Add custom group</h2><form className="form-grid" onSubmit={submit}><label>Group code<input name="code" pattern="[0-9]{4}" required /></label><label>Group name<input name="name" required /></label><label>Classification<select name="classification">{["asset", "liability", "equity", "income", "expense"].map((item) => <option key={item}>{item}</option>)}</select></label><button className="button">Add group</button></form>{message && <p className="form-message">{message}</p>}</section></>; }
function Years({ rows, run, message }: { rows: Row[]; run: (work: Promise<{ ok?: true; error?: string }>) => void; message: string }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(saveFinancialYear({ name: String(form.get("name")), startDate: String(form.get("start")), endDate: String(form.get("end")), isDefault: form.get("default") === "on" })); }; return <><section className="panel"><div className="panel-head"><h2>Financial Years</h2></div><SimpleTable rows={rows} /></section><section className="panel form-panel"><h2>Add financial year</h2><form className="form-grid" onSubmit={submit}><label>Name<input name="name" required /></label><label>Start<input name="start" type="date" required /></label><label>End<input name="end" type="date" required /></label><label className="check-label"><input type="checkbox" name="default" /> Default year</label><button className="button">Save year</button></form>{message && <p className="form-message">{message}</p>}</section></>; }
function Sequences({ rows, run, message }: { rows: Row[]; run: (work: Promise<{ ok?: true; error?: string }>) => void; message: string }) { const [editing, setEditing] = useState<string | null>(null); const row = rows.find((item) => String(item.id) === editing); return <section className="panel"><div className="panel-head"><div><h2>Document Numbering</h2><p>Numbers are configured here; atomic assignment arrives with document posting.</p></div></div><table className="data-table"><thead><tr><th>Document</th><th>Prefix</th><th>Next Number</th><th>Preview</th><th /></tr></thead><tbody>{rows.map((item) => <tr key={String(item.id)}><td>{label(String(item.document_type))}</td><td>{String(item.prefix)}</td><td>{String(item.next_number)}</td><td>{String(item.prefix)}{String(item.next_number).padStart(Number(item.padding), "0")}{String(item.suffix || "")}</td><td><button className="text-button" onClick={() => setEditing(String(item.id))}>Edit</button></td></tr>)}</tbody></table>{row ? <form className="form-grid sequence-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(saveDocumentSequence({ id: String(row.id), prefix: String(form.get("prefix")), nextNumber: Number(form.get("next")), padding: Number(form.get("padding")), suffix: String(form.get("suffix")) })); setEditing(null); }}><label>Prefix<input name="prefix" defaultValue={String(row.prefix)} /></label><label>Next number<input name="next" type="number" min="1" defaultValue={String(row.next_number)} /></label><label>Padding<input name="padding" type="number" min="1" max="12" defaultValue={String(row.padding)} /></label><label>Suffix<input name="suffix" defaultValue={String(row.suffix || "")} /></label><button className="button">Save numbering</button></form> : null}{message && <p className="form-message">{message}</p>}</section>; }
function Opening({ rows }: { rows: Row[] }) { return <section className="panel"><h2>Opening Balances</h2><p>Create a balanced draft when your opening figures are ready. Drafts do not update cash, bank, or ledger balances.</p>{rows.length?<table className="data-table"><thead><tr><th>Date</th><th>Status</th><th>Notes</th><th>Posted journal</th></tr></thead><tbody>{rows.map(row=>{const journal=row.journal_entries as {journal_number?:string}|null;return <tr key={String(row.id)}><td>{String(row.opening_date)}</td><td>{String(row.status)}</td><td>{String(row.notes||"—")}</td><td>{row.posted_journal_id?<Link className="text-button" href={`/accounting/journals/${String(row.posted_journal_id)}`}>{journal?.journal_number||"View posted journal"}</Link>:"Draft — not posted"}</td></tr>})}</tbody></table>:<p className="empty-state">No opening balance drafts yet.</p>}</section>; }
function OperationalForm({ kind, run, message }: { kind: "cash" | "bank" | "tax"; run: (work: Promise<{ ok?: true; error?: string }>) => void; message: string }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (kind === "tax") run(createTaxRate({ code: String(form.get("code")), name: String(form.get("name")), rate: Number(form.get("rate")), treatment: String(form.get("treatment")) })); else run(createOperationalAccount({ kind, name: String(form.get("name")), code: String(form.get("code")), bankName: String(form.get("bank")), maskedNumber: String(form.get("masked")), iban: String(form.get("iban")) })); event.currentTarget.reset(); }; return <section className="panel form-panel"><h2>Add {kind === "tax" ? "tax rate" : `${kind} account`}</h2><form className="form-grid" onSubmit={submit}>{kind === "bank" ? <label>Bank name<input name="bank" required /></label> : null}<label>{kind === "tax" ? "Code" : "Account name"}<input name={kind === "tax" ? "code" : "name"} required /></label>{kind === "tax" ? <><label>Name<input name="name" required /></label><label>Rate %<input name="rate" type="number" min="0" max="100" step="0.01" required /></label><label>Treatment<select name="treatment"><option value="standard">Standard rated</option><option value="zero_rated">Zero rated</option><option value="exempt">Exempt</option><option value="out_of_scope">Out of scope</option></select></label></> : <><label>Ledger code<input name="code" pattern="[0-9]{4}" required /></label>{kind === "bank" ? <><label>Masked account number<input name="masked" placeholder="•••• 1234" /></label><label>IBAN<input name="iban" /></label></> : null}</>}<button className="button">Create</button></form>{message && <p className="form-message">{message}</p>}</section>; }
function SimpleTable({ rows, empty = "No records." }: { rows: Row[]; empty?: string }) { if (!rows.length) return <p className="empty-state">{empty}</p>; const keys = Object.keys(rows[0]).filter((key) => !["id", "organization_id", "created_at", "updated_at", "account_id", "branch_id", "financial_year_id", "input_account_id", "output_account_id"].includes(key)).slice(0, 6); return <table className="data-table"><thead><tr>{keys.map((key) => <th key={key}>{label(key)}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)}>{keys.map((key) => <td key={key}>{typeof row[key] === "boolean" ? (row[key] ? "Yes" : "No") : String(row[key] ?? "—")}</td>)}</tr>)}</tbody></table>; }
