"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { getConversionSources, getSalesWorkflowData, saveOperationalDocument, type SalesWorkflowData } from "@/app/actions/sales-workflow";
import { dubaiCalendarDate } from "@/lib/dubai-date";

type Kind="quotation"|"delivery_note"|"invoice";
const today=()=>dubaiCalendarDate(), money=(v:unknown)=>new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED"}).format(Number(v||0));
function dates(preset:string){const d=new Date(`${today()}T12:00:00+04:00`), start=new Date(d); if(preset==="today")return [dubaiCalendarDate(d),dubaiCalendarDate(d)]; if(preset==="yesterday"){d.setUTCDate(d.getUTCDate()-1);return[dubaiCalendarDate(d),dubaiCalendarDate(d)]} if(preset==="week"){start.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return[dubaiCalendarDate(start),dubaiCalendarDate(d)]} if(preset==="month"){start.setUTCDate(1);return[dubaiCalendarDate(start),dubaiCalendarDate(d)]} start.setUTCMonth(d.getUTCMonth()-1,1); const end=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),0,12)); return[dubaiCalendarDate(start),dubaiCalendarDate(end)];}
export function SalesWorkflow({kind,mode}:{kind:Kind;mode:"list"|"new"}){return mode==="new"&&kind!=="invoice"?<Editor kind={kind}/>:<List kind={kind}/>}

function List({kind}:{kind:Kind}){
 const router=useRouter(),sp=useSearchParams(),[data,setData]=useState<SalesWorkflowData|null>(null),[error,setError]=useState(""),[selected,setSelected]=useState<string[]>([]),
 [filters,setFilters]=useState({search:sp.get("search")||"",customerId:sp.get("customer")||"",productId:sp.get("item")||"",from:sp.get("from")||"",to:sp.get("to")||"",status:sp.get("status")||"",page:Number(sp.get("page")||1)});
 const load=useCallback(async()=>{const r=await getSalesWorkflowData(kind,{...filters,customerId:filters.customerId||undefined,productId:filters.productId||undefined,from:filters.from||undefined,to:filters.to||undefined,status:filters.status||undefined});if("error"in r)setError(r.error);else{setData(r);setError("")}},[kind,filters]); useEffect(()=>{void load()},[load]);
 function apply(next=filters){setFilters(next);const q=new URLSearchParams();if(next.search)q.set("search",next.search);if(next.customerId)q.set("customer",next.customerId);if(next.productId)q.set("item",next.productId);if(next.from)q.set("from",next.from);if(next.to)q.set("to",next.to);if(next.status)q.set("status",next.status);if(next.page>1)q.set("page",String(next.page));router.replace(`/${kind==="quotation"?"sales/quotations":kind==="delivery_note"?"sales/delivery-notes":"sales/invoices"}?${q}`)}
 if(!data)return <><Header kind={kind}/>{error?<p className="error">{error}</p>:<section className="panel">Loading documents…</section>}</>;
 const docs=kind==="quotation"?data.quotations:kind==="delivery_note"?data.deliveryNotes:data.invoices, lines=kind==="quotation"?data.quotationLines:kind==="delivery_note"?data.deliveryLines:data.invoiceLines,
 number=(x:any)=>x.quotation_number||x.delivery_note_number||x.invoice_number||"Draft", date=(x:any)=>x.quotation_date||x.delivery_date||x.invoice_date,
 fk=kind==="quotation"?"quotation_id":kind==="delivery_note"?"delivery_note_id":"invoice_id";
 const state=(id:string)=>{if(kind==="invoice")return null;const sourceType=kind, own=lines.filter((x:any)=>x[fk]===id),used=data.conversions.filter((x:any)=>x.source_type===sourceType&&x.source_document_id===id).reduce((s:number,x:any)=>s+Number(x.quantity),0),total=own.reduce((s:number,x:any)=>s+Number(x.quantity),0),word=kind==="delivery_note"?"Invoiced":"Converted";return used<=0?`Not ${word}`:used>=total?`Fully ${word}`:`Partially ${word}`};
 const selectedDocs=docs.filter((x:any)=>selected.includes(x.id)), compatible=selectedDocs.length>0&&new Set(selectedDocs.map((x:any)=>`${x.customer_id}:${x.branch_id}`)).size===1;
 return <><Header kind={kind}/><section className="panel toolbar report-toolbar filter-panel">
  <input aria-label="Search documents" placeholder="Number, customer, item, SKU or reference" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/>
  <select aria-label="Customer" value={filters.customerId} onChange={e=>setFilters({...filters,customerId:e.target.value})}><option value="">All customers</option>{data.customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
  <select aria-label="Item" value={filters.productId} onChange={e=>setFilters({...filters,productId:e.target.value})}><option value="">All items</option>{data.products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
  {kind!=="invoice"&&<select aria-label="Conversion status" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option><option value="not_converted">{kind==="delivery_note"?"Not Invoiced":"Not Converted"}</option><option value="partial">{kind==="delivery_note"?"Partially Invoiced":"Partially Converted"}</option><option value="full">{kind==="delivery_note"?"Fully Invoiced":"Fully Converted"}</option></select>}
  <select aria-label="Date preset" defaultValue="" onChange={e=>{if(e.target.value){const [from,to]=dates(e.target.value);apply({...filters,from,to})}}}><option value="">Date preset</option><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="week">This Week</option><option value="month">This Month</option><option value="last">Last Month</option></select>
  <input aria-label="From date" type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input aria-label="To date" type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/>
  <button className="button secondary" onClick={()=>apply({...filters,page:1})}>Apply</button><button className="text-button" onClick={()=>apply({search:"",customerId:"",productId:"",from:"",to:"",status:"",page:1})}>Clear Filters</button>
 </section>
 {selected.length>0&&kind!=="invoice"&&<section className="panel selection-bar"><strong>{selected.length} selected</strong>{compatible?<span>{kind==="quotation"&&<Link className="button secondary" href={`/sales/delivery-notes/new?sourceType=quotation&sourceIds=${selected.join(",")}`}>Create Delivery Note</Link>}<Link className="button" href={`/sales/invoices/new?sourceType=${kind}&sourceIds=${selected.join(",")}`}>Create Sales Invoice</Link></span>:<span className="error">Selected documents must belong to the same customer and branch.</span>}</section>}
 <section className="panel"><div className="table-wrap"><table><thead><tr>{kind!=="invoice"&&<th><span className="sr-only">Select</span></th>}<th>Document</th><th>Date</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{docs.map((x:any)=>{const own=lines.filter((l:any)=>l[fk]===x.id), total=own.reduce((s:number,l:any)=>{const net=Number(l.quantity)*Number(l.unit_price)-Number(l.discount||0),tax=Number(data.taxRates.find(t=>t.id===l.tax_rate_id)?.rate_percent||0);return s+net*(1+tax/100)},0);return <tr key={x.id}>{kind!=="invoice"&&<td><input type="checkbox" aria-label={`Select ${number(x)}`} checked={selected.includes(x.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,x.id]:v.filter(id=>id!==x.id))}/></td>}<td><b>{number(x)}</b></td><td>{date(x)}</td><td>{x.customers?.name}</td><td>{own.map((l:any)=>l.products?.name||l.description).join(", ")}</td><td>{kind==="invoice"?money(x.grand_total):money(total)}</td><td><span className={`badge ${state(x.id)?.startsWith("Fully")?"b-posted":""}`}>{state(x.id)||x.status}</span></td><td><Link className="record-link" href={`/documents/${kind==="delivery_note"?"delivery-note":kind}/${x.id}`}>Print / PDF</Link></td></tr>})}</tbody></table></div>{!docs.length&&<p className="empty">No documents match the selected filters.</p>}{data.totalCount>data.pageSize&&<div className="selection-bar"><button className="text-button" disabled={data.page<=1} onClick={()=>apply({...filters,page:data.page-1})}>Previous</button><span>Page {data.page} of {Math.ceil(data.totalCount/data.pageSize)}</span><button className="text-button" disabled={data.page*data.pageSize>=data.totalCount} onClick={()=>apply({...filters,page:data.page+1})}>Next</button></div>}</section></>;
}
function Header({kind}:{kind:Kind}){const title=kind==="quotation"?"Quotations":kind==="delivery_note"?"Delivery Notes":"Sales Invoices";return <div className="page-header"><div><h1>{title}</h1><p>Search by customer, item, SKU, reference, and date. Filters persist in the URL.</p></div>{kind!=="invoice"&&<Link className="button" href={`/${kind==="quotation"?"sales/quotations":"sales/delivery-notes"}/new`}>+ New</Link>}</div>}

function Editor({kind}:{kind:Exclude<Kind,"invoice">}){
 const router=useRouter(),sp=useSearchParams(),sourceType=sp.get("sourceType") as "quotation"|"delivery_note"|null,sourceIds=sp.get("sourceIds")||"",[data,setData]=useState<SalesWorkflowData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[customerId,setCustomer]=useState(""),[date,setDate]=useState(today()),[expiry,setExpiry]=useState(today()),[reference,setReference]=useState(""),[notes,setNotes]=useState(""),[lines,setLines]=useState<any[]>([]);
 const dirty=useRef({customer:false,reference:false,lines:false});
 useEffect(()=>{void getSalesWorkflowData("quotation",{}).then(async r=>{if("error"in r){setError(r.error||"Unable to load documents.");return}setData(r);if(!dirty.current.customer)setCustomer(r.customers[0]?.id||"");const ids=sourceIds.split(",").filter(Boolean);if(sourceType&&ids.length){const s=await getConversionSources(sourceType,ids);if("error"in s){setError(s.error||"Unable to load conversion sources.");return}if(!dirty.current.customer)setCustomer(s.customerId);if(!dirty.current.reference)setReference(`Created from ${s.documents.map((x:any)=>x.quotation_number||x.delivery_note_number).join(", ")}`);if(!dirty.current.lines)setLines(s.lines.map((x:any)=>({productId:x.product_id,description:x.description,quantity:x.remaining,unitPrice:Number(x.unit_price),discount:Number(x.discount),taxRateId:x.tax_rate_id||"",accountId:x.revenue_account_id,sourceType:x.sourceType,sourceDocumentId:x.sourceDocumentId,sourceLineId:x.id,remaining:x.remaining})));}else if(!dirty.current.lines)setLines([fresh(r)]);})},[sourceType,sourceIds]);
 if(!data)return <section className="panel">{error||"Loading editor…"}</section>; const change=(i:number,v:any)=>setLines(a=>a.map((x,n)=>n===i?{...x,...v}:x)), choose=(i:number,id:string)=>{const p=data.products.find(x=>x.id===id);change(i,{productId:id,description:p?.name||"",unitPrice:Number(p?.sales_price||0),taxRateId:p?.tax_rate_id||""})};
 async function save(){setBusy(true);const r=await saveOperationalDocument({kind,customerId,date,expiry:kind==="quotation"?expiry:undefined,reference,notes,lines,allocations:lines.filter(x=>x.sourceLineId).map(x=>({sourceType:x.sourceType,sourceDocumentId:x.sourceDocumentId,sourceLineId:x.sourceLineId,quantity:x.quantity}))});if("error"in r){setError(r.error||"Unable to save document.");setBusy(false);return}router.push(kind==="quotation"?"/sales/quotations":"/sales/delivery-notes");router.refresh()}
 return <><div className="page-header"><div><h1>New {kind==="quotation"?"quotation":"delivery note"}</h1><p>Review source quantities, reduce for a partial conversion, or add additional items.</p></div></div><section className="panel form-panel"><div className="form-grid"><label>Customer<select value={customerId} onChange={e=>{dirty.current.customer=true;setCustomer(e.target.value)}}>{data.customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{kind==="quotation"&&<label>Expiry<input type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label>}<label>Reference<input value={reference} onChange={e=>{dirty.current.reference=true;setReference(e.target.value)}}/></label></div><div className="line-head"><h2>Items</h2><button className="text-button" onClick={()=>{dirty.current.lines=true;setLines(v=>[...v,fresh(data)])}}>+ Add item</button></div><div className="line-editor">{lines.map((l,i)=><div className="line-row" key={i}><label>Product<select value={l.productId} onChange={e=>{dirty.current.lines=true;choose(i,e.target.value)}}>{data.products.map(x=><option key={x.id} value={x.id}>{x.name} {x.inventory_units?.code?`(${x.inventory_units.code})`:""}</option>)}</select></label><label>Quantity<input type="number" min="0.0001" step="0.0001" max={l.remaining} value={l.quantity} onChange={e=>{dirty.current.lines=true;change(i,{quantity:Number(e.target.value)})}}/></label><label>Unit price<input type="number" min="0" value={l.unitPrice} onChange={e=>{dirty.current.lines=true;change(i,{unitPrice:Number(e.target.value)})}}/></label><label>Discount<input type="number" min="0" value={l.discount} onChange={e=>{dirty.current.lines=true;change(i,{discount:Number(e.target.value)})}}/></label>{l.sourceLineId&&<span className="notice">Source quantity · remaining {l.remaining}</span>}<button className="icon-button" onClick={()=>{dirty.current.lines=true;setLines(v=>v.filter((_,n)=>n!==i))}}>×</button></div>)}</div><label className="wide-label">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<div className="form-actions"><button className="button" disabled={busy||!lines.length} onClick={()=>void save()}>Save {kind==="quotation"?"quotation":"delivery note"}</button></div></section></>;
}
function fresh(data:SalesWorkflowData){const p=data.products[0];return{productId:p?.id||"",description:p?.name||"",quantity:1,unitPrice:Number(p?.sales_price||0),discount:0,taxRateId:p?.tax_rate_id||"",accountId:data.accounts[0]?.id||""}}
