"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { getOpenItemReport, getStatementReport, type ReportData } from "@/app/actions/statements";
import { useOrganizationContext } from "@/components/app-shell";
const money=(x:unknown)=>new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED"}).format(Number(x||0));
const csv=(name:string,headers:string[],rows:any[][],metadata:any[][]=[],footer:any[]=[])=>{const quote=(x:any)=>`"${String(x??"").replaceAll('"','""')}"`;const lines=[...metadata,...(metadata.length?[[]]:[]),headers,...rows,...(footer.length?[[],footer]:[])];const content=lines.map(x=>x.map(quote).join(",")).join("\n");const stamp=new Date().toISOString().replaceAll(":","-").replace("T","-").slice(0,19);const a=document.createElement("a");a.href=`data:text/csv;charset=utf-8,${encodeURIComponent(content)}`;a.download=name.replace(/\.csv$/,`-${stamp}.csv`);document.body.appendChild(a);a.click();a.remove()};
const today=new Date().toISOString().slice(0,10), first=`${today.slice(0,8)}01`;
export function StatementsReports({kind}:{kind:"customer"|"supplier"|"ar"|"ap"}){const {branch:activeBranch}=useOrganizationContext();const partyType=kind==="customer"||kind==="ar"?"customer":"supplier";const statement=kind==="customer"||kind==="supplier";const [from,setFrom]=useState(first),[to,setTo]=useState(today),[party,setParty]=useState(""),[branch,setBranch]=useState(activeBranch.id),[state,setState]=useState("open"),[data,setData]=useState<ReportData|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{const result=statement?await getStatementReport({partyType,partyId:party||undefined,from,to,branchId:branch||undefined,state:"open"}):await getOpenItemReport({partyType,from,to,branchId:branch||undefined,state:state as any});if("error" in result)setError(result.error);else{setData(result);setError("");}},[branch,from,party,partyType,state,statement,to]);useEffect(()=>{void load()},[load]);
 const parties=partyType==="customer"?data?.customers||[]:data?.suppliers||[];const rows=data?.openItems;const outstanding=useMemo(()=>(rows||[]).reduce((s,x)=>s+Number(x.outstanding||0),0),[rows]);const title=statement?`${partyType==="customer"?"Customer":"Supplier"} Statement`:`Accounts ${partyType==="customer"?"Receivable":"Payable"}`;
 return <><div className="page-header"><div><h1>{title}</h1><p>Live posted accounting activity and open items.</p></div></div><section className="panel toolbar report-toolbar"><select value={party} onChange={e=>setParty(e.target.value)} disabled={!statement}><option value="">Select {partyType}</option>{parties.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">All branches</option>{data?.branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{!statement&&<select value={state} onChange={e=>setState(e.target.value)}><option value="open">Open</option><option value="settled">Settled</option><option value="all">All</option></select>}<button className="button" onClick={()=>void load()}>{statement?"Run statement":"Run report"}</button></section>{error&&<p className="error">{error}</p>}{statement?<Statement data={data?.statement} party={parties.find(x=>x.id===party)?.name} type={partyType} from={from} to={to}/>:<Open data={rows||[]} type={partyType} outstanding={outstanding} asOf={to}/>}</>}
const sourcePath=(type:string,id:string)=>type==="Sales Invoice"?`/sales/invoices/${id}`:type==="Sales Credit Note"?`/sales/credit-notes/${id}`:type==="Customer Receipt"?`/sales/customer-payments/${id}`:type==="Purchase Bill"?`/purchases/bills/${id}`:type==="Purchase Debit Note"?`/purchases/debit-notes/${id}`:`/purchases/supplier-payments/${id}`;
function Statement({data,party,type,from,to}:{data?:any;party?:string;type:string;from:string;to:string}){if(!party)return <section className="panel empty">Choose a {type} to run a real statement.</section>;const rows=data?.rows||[];return <section className="panel report-panel"><div className="panel-head"><div><h2>{party}</h2><p>Opening and running balances use posted transactions before and within this date range.</p></div><button className="button secondary" onClick={()=>csv(`${type}-statement.csv`,["Date","Type","Document","Reference","Debit","Credit","Balance"],rows.map((x:any)=>[x.transaction_date,x.transaction_type,x.document_number,x.reference,x.debit,x.credit,x.running_balance]),[[type==="customer"?"Customer":"Supplier",party],["From Date",from],["To Date",to],["Opening Balance",data?.opening]], ["Closing Balance","","","","","",data?.closing])}>Export CSV</button></div><div className="totals"><span>Opening <b>{money(data?.opening)}</b></span><span>Invoiced / Bills <b>{money(data?.invoiced)}</b></span><span>Credits <b>{money(data?.credits)}</b></span><span>Receipts / Payments <b>{money(data?.receipts)}</b></span><strong>Closing <b>{money(data?.closing)}</b></strong></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Document</th><th>Reference</th><th>Debit</th><th>Credit</th><th>Balance</th><th>Journal</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.document_id}><td>{x.transaction_date}</td><td>{x.transaction_type}</td><td><Link className="record-link" href={sourcePath(x.transaction_type,x.document_id)}>{x.document_number}</Link></td><td>{x.reference||"—"}</td><td className="amount">{money(x.debit)}</td><td className="amount">{money(x.credit)}</td><td className="amount">{money(x.running_balance)}</td><td>{x.posted_journal_id&&<Link className="record-link" href={`/accounting/journals/${x.posted_journal_id}`}>View JV</Link>}</td></tr>)}</tbody></table></div></section>}
function Open({data,type,outstanding,asOf}:{data:any[];type:string;outstanding:number;asOf:string}){const noun=type==="customer"?"Invoices":"Bills";return <section className="panel report-panel"><div className="panel-head"><div><h2>Open {noun}</h2><p>Age is based on reliable due dates.</p></div><button className="button secondary" onClick={()=>csv(type==="customer"?"accounts-receivable.csv":"accounts-payable.csv",["Party","Document","Date","Due date","Original","Allocated","Outstanding","Status","Age","Bucket"],data.map(x=>[x.party_name,x.document_number,x.document_date,x.due_date,x.original_amount,x.allocated_amount,x.outstanding,x.item_status,x.age_days,x.bucket]),[["As Of",asOf]], ["Total Outstanding","","","","","",outstanding])}>Export CSV</button></div><div className="totals"><strong>Total Outstanding <b>{money(outstanding)}</b></strong><span>Open {noun} <b>{data.filter(x=>x.item_status!=="settled").length}</b></span></div><div className="table-wrap"><table><thead><tr><th>{type==="customer"?"Customer":"Supplier"}</th><th>{noun.slice(0,-1)}</th><th>Date</th><th>Due</th><th>Original</th><th>Allocated</th><th>Outstanding</th><th>Status</th><th>Age</th><th>Journal</th></tr></thead><tbody>{data.map(x=><tr key={x.open_item_id}><td>{x.party_name}</td><td><Link className="record-link" href={type==="customer"?`/sales/invoices/${x.document_id}`:`/purchases/bills/${x.document_id}`}>{x.document_number}</Link></td><td>{x.document_date}</td><td>{x.due_date||"—"}</td><td>{money(x.original_amount)}</td><td>{money(x.allocated_amount)}</td><td>{money(x.outstanding)}</td><td>{x.item_status==="open"?"Unpaid":x.item_status==="partial"?"Partially Paid":"Paid"}</td><td>{x.bucket} ({x.age_days}d)</td><td>{x.posted_journal_id&&<Link className="record-link" href={`/accounting/journals/${x.posted_journal_id}`}>View JV</Link>}</td></tr>)}</tbody></table></div></section>}
