create extension if not exists pgcrypto;

create type public.membership_status as enum ('active','inactive');
create type public.entity_status as enum ('active','inactive');

create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path = public as $$ begin new.updated_at = now(); return new; end; $$;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null check (length(trim(name)) > 0), legal_name text, slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'), base_currency text not null default 'AED' check (base_currency = 'AED'), timezone text not null default 'Asia/Dubai', status public.entity_status not null default 'active', created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.branches (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null check(length(trim(name))>0), code text, status public.entity_status not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id, name));
create table public.organization_memberships (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, membership_status public.membership_status not null default 'active', is_owner boolean not null default false, default_branch_id uuid references public.branches(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,user_id));
create table public.organization_settings (id uuid primary key default gen_random_uuid(), organization_id uuid not null unique references public.organizations(id) on delete cascade, setting_value jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audit_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), branch_id uuid references public.branches(id), actor_user_id uuid references auth.users(id), actor_membership_id uuid references public.organization_memberships(id), event_type text not null, entity_type text not null, entity_id uuid, correlation_id uuid not null default gen_random_uuid(), metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index memberships_user_org_idx on public.organization_memberships(user_id,organization_id) where membership_status='active'; create index branches_org_idx on public.branches(organization_id); create index audit_events_org_idx on public.audit_events(organization_id,created_at desc);
create or replace function public.is_active_org_member(p_org uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.organization_memberships m where m.organization_id=p_org and m.user_id=(select auth.uid()) and m.membership_status='active') $$;
create or replace function public.is_org_owner(p_org uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.organization_memberships m where m.organization_id=p_org and m.user_id=(select auth.uid()) and m.membership_status='active' and m.is_owner) $$;
revoke all on function public.is_active_org_member(uuid), public.is_org_owner(uuid) from public; grant execute on function public.is_active_org_member(uuid), public.is_org_owner(uuid) to authenticated;
create or replace function public.create_organization(p_name text,p_legal_name text,p_slug text,p_branch_name text) returns uuid language plpgsql security definer set search_path=public as $$ declare oid uuid:=gen_random_uuid(); bid uuid:=gen_random_uuid(); mid uuid:=gen_random_uuid(); begin if auth.uid() is null then raise exception 'unauthenticated'; end if; if exists(select 1 from organizations where slug=p_slug) then raise exception 'slug_taken'; end if; if coalesce(trim(p_name),'')='' or coalesce(trim(p_branch_name),'')='' then raise exception 'invalid_input'; end if; insert into profiles(id) values(auth.uid()) on conflict do nothing; insert into organizations(id,name,legal_name,slug,created_by) values(oid,trim(p_name),nullif(trim(p_legal_name),''),p_slug,auth.uid()); insert into branches(id,organization_id,name) values(bid,oid,trim(p_branch_name)); insert into organization_memberships(id,organization_id,user_id,is_owner,default_branch_id) values(mid,oid,auth.uid(),true,bid); insert into organization_settings(organization_id) values(oid); insert into audit_events(organization_id,branch_id,actor_user_id,actor_membership_id,event_type,entity_type,entity_id) values(oid,bid,auth.uid(),mid,'organization.created','organization',oid),(oid,bid,auth.uid(),mid,'branch.created','branch',bid); return oid; end $$;
revoke all on function public.create_organization(text,text,text,text) from public; grant execute on function public.create_organization(text,text,text,text) to authenticated;
do $$ declare t text; begin foreach t in array array['profiles','organizations','branches','organization_memberships','organization_settings','audit_events'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy profile_self_select on public.profiles for select to authenticated using(id=(select auth.uid())); create policy profile_self_update on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy org_member_select on public.organizations for select to authenticated using(public.is_active_org_member(id));
create policy membership_member_select on public.organization_memberships for select to authenticated using(public.is_active_org_member(organization_id));
create policy branch_member_select on public.branches for select to authenticated using(public.is_active_org_member(organization_id)); create policy branch_owner_insert on public.branches for insert to authenticated with check(public.is_org_owner(organization_id)); create policy branch_owner_update on public.branches for update to authenticated using(public.is_org_owner(organization_id)) with check(public.is_org_owner(organization_id));
create policy settings_member_select on public.organization_settings for select to authenticated using(public.is_active_org_member(organization_id)); create policy settings_owner_update on public.organization_settings for update to authenticated using(public.is_org_owner(organization_id)) with check(public.is_org_owner(organization_id));
create policy audit_member_select on public.audit_events for select to authenticated using(public.is_active_org_member(organization_id));
grant select,update on public.profiles to authenticated; grant select on public.organizations,public.organization_memberships,public.audit_events to authenticated; grant select,insert,update on public.branches to authenticated; grant select,update on public.organization_settings to authenticated;
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at(); create trigger organizations_updated before update on public.organizations for each row execute function public.set_updated_at(); create trigger branches_updated before update on public.branches for each row execute function public.set_updated_at(); create trigger memberships_updated before update on public.organization_memberships for each row execute function public.set_updated_at(); create trigger settings_updated before update on public.organization_settings for each row execute function public.set_updated_at();
