-- Preserve the existing receipt posting contract while typing open-item status explicitly.
create or replace function public.post_customer_receipt(p_organization_id uuid,p_receipt_id uuid,p_allocations jsonb default '[]'::jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare d public.customer_receipts%rowtype;x jsonb;i public.open_items%rowtype;l public.customer_receipt_payment_legs%rowtype;v_total numeric:=0;v_leg_total numeric:=0;v_amount numeric;v_journal uuid:=gen_random_uuid();v_ar uuid;v_n bigint;v_prefix text;v_padding smallint;v_suffix text;v_line smallint:=0;begin
 perform public.assert_accounting_owner(p_organization_id);perform public.assert_unique_settlement_allocation_targets(p_organization_id,p_allocations);select * into d from public.customer_receipts where id=p_receipt_id and organization_id=p_organization_id for update;if not found then raise exception 'not_found';end if;if d.status='posted' then return jsonb_build_object('receipt_id',d.id,'journal_id',d.posted_journal_id,'already_posted',true);end if;
 for x in select value from jsonb_array_elements(p_allocations) loop v_amount:=(x->>'amount')::numeric;select * into i from public.open_items where id=(x->>'open_item_id')::uuid and organization_id=p_organization_id for update;if not found or i.kind<>'receivable' or i.customer_id<>d.customer_id or v_amount<=0 or v_amount>i.remaining_amount then raise exception 'invalid_receipt_allocation';end if;v_total:=v_total+v_amount;end loop;if round(v_total,6)<>round(d.amount,6) then raise exception 'receipt_allocation_must_equal_amount';end if;
 select id into v_ar from public.accounts where organization_id=p_organization_id and system_key='accounts_receivable' and is_active;if v_ar is null then raise exception 'system_account_missing';end if;
 insert into public.journal_entries(id,organization_id,branch_id,journal_date,source_type,source_id,description,created_by) values(v_journal,p_organization_id,d.branch_id,d.receipt_date,'customer_receipt',d.id,'Customer receipt',auth.uid());
 for l in select * from public.customer_receipt_payment_legs where customer_receipt_id=d.id order by created_at,id loop v_leg_total:=v_leg_total+l.amount;v_line:=v_line+1;insert into public.journal_lines(organization_id,journal_entry_id,line_number,account_id,description,debit_amount,credit_amount,branch_id) values(p_organization_id,v_journal,v_line,l.account_id,'Customer receipt · '||replace(l.method,'_',' '),l.amount,0,d.branch_id);end loop;
 if round(v_leg_total,6)<>round(d.amount,6) then raise exception 'payment_legs_must_equal_amount';end if;v_line:=v_line+1;insert into public.journal_lines(organization_id,journal_entry_id,line_number,account_id,description,debit_amount,credit_amount,party_type,party_id,branch_id) values(p_organization_id,v_journal,v_line,v_ar,'Accounts receivable',0,d.amount,'customer',d.customer_id,d.branch_id);
 select prefix,padding,suffix,next_number into v_prefix,v_padding,v_suffix,v_n from public.document_sequences where organization_id=p_organization_id and document_type='receipt' and branch_id is null and financial_year_id is null for update;update public.document_sequences set next_number=next_number+1 where organization_id=p_organization_id and document_type='receipt' and branch_id is null and financial_year_id is null;update public.journal_entries set reference=v_prefix||lpad(v_n::text,v_padding,'0')||coalesce(v_suffix,'') where id=v_journal;perform public.post_journal_entry(p_organization_id,v_journal);
 for x in select value from jsonb_array_elements(p_allocations) loop v_amount:=(x->>'amount')::numeric;update public.open_items set remaining_amount=remaining_amount-v_amount,status=(case when remaining_amount-v_amount=0 then 'settled' else 'partial' end)::public.open_item_status where id=(x->>'open_item_id')::uuid;insert into public.open_item_allocations(organization_id,open_item_id,customer_receipt_id,amount) values(p_organization_id,(x->>'open_item_id')::uuid,d.id,v_amount);end loop;
 update public.customer_receipts set receipt_number=v_prefix||lpad(v_n::text,v_padding,'0')||coalesce(v_suffix,''),status='posted',posted_journal_id=v_journal,posted_at=now(),posted_by=auth.uid() where id=d.id;perform public.accounting_audit(p_organization_id,'customer_receipt.posted','customer_receipt',d.id);return jsonb_build_object('receipt_id',d.id,'journal_id',v_journal,'already_posted',false);
end $$;

revoke all on function public.post_customer_receipt(uuid,uuid,jsonb) from public,anon;
grant execute on function public.post_customer_receipt(uuid,uuid,jsonb) to authenticated,service_role;
