-- Phase 2 operational master creation. These records still do not create postings or balances.
create or replace function public.create_cash_account(p_organization_id uuid,p_name text,p_account_code text,p_branch_id uuid default null) returns uuid language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_account_id uuid:=gen_random_uuid(); v_id uuid:=gen_random_uuid(); v_group_id uuid;
begin perform public.assert_accounting_owner(p_organization_id); select id into v_group_id from public.account_groups where organization_id=p_organization_id and system_key='cash'; if v_group_id is null or (p_branch_id is not null and not exists(select 1 from public.branches where id=p_branch_id and organization_id=p_organization_id)) then raise exception 'invalid_reference'; end if; insert into public.accounts(id,organization_id,account_group_id,code,name,account_type) values(v_account_id,p_organization_id,v_group_id,trim(p_account_code),trim(p_name),'cash'); insert into public.cash_accounts(id,organization_id,account_id,branch_id,name) values(v_id,p_organization_id,v_account_id,p_branch_id,trim(p_name)); perform public.accounting_audit(p_organization_id,'cash_account.created','cash_account',v_id); return v_id; end; $$;
create or replace function public.create_bank_account(p_organization_id uuid,p_bank_name text,p_account_name text,p_account_code text,p_account_number_masked text default null,p_iban text default null,p_branch_id uuid default null) returns uuid language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_account_id uuid:=gen_random_uuid(); v_id uuid:=gen_random_uuid(); v_group_id uuid;
begin perform public.assert_accounting_owner(p_organization_id); select id into v_group_id from public.account_groups where organization_id=p_organization_id and system_key='bank'; if v_group_id is null or (p_branch_id is not null and not exists(select 1 from public.branches where id=p_branch_id and organization_id=p_organization_id)) then raise exception 'invalid_reference'; end if; insert into public.accounts(id,organization_id,account_group_id,code,name,account_type) values(v_account_id,p_organization_id,v_group_id,trim(p_account_code),trim(p_account_name),'bank'); insert into public.bank_accounts(id,organization_id,account_id,branch_id,bank_name,account_name,account_number_masked,iban) values(v_id,p_organization_id,v_account_id,p_branch_id,trim(p_bank_name),trim(p_account_name),nullif(trim(p_account_number_masked),''),nullif(trim(p_iban),'')); perform public.accounting_audit(p_organization_id,'bank_account.created','bank_account',v_id); return v_id; end; $$;
create or replace function public.create_tax_rate(p_organization_id uuid,p_code text,p_name text,p_rate_percent numeric,p_treatment public.tax_treatment,p_sales_enabled boolean default true,p_purchase_enabled boolean default true) returns uuid language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_id uuid:=gen_random_uuid(); begin perform public.assert_accounting_owner(p_organization_id); insert into public.tax_rates(id,organization_id,code,name,rate_percent,treatment,sales_enabled,purchase_enabled) values(v_id,p_organization_id,trim(p_code),trim(p_name),p_rate_percent,p_treatment,p_sales_enabled,p_purchase_enabled); perform public.accounting_audit(p_organization_id,'tax_rate.created','tax_rate',v_id); return v_id; end; $$;
revoke all on function public.create_cash_account(uuid,text,text,uuid),public.create_bank_account(uuid,text,text,text,text,text,uuid),public.create_tax_rate(uuid,text,text,numeric,public.tax_treatment,boolean,boolean) from public,anon;
grant execute on function public.create_cash_account(uuid,text,text,uuid),public.create_bank_account(uuid,text,text,text,text,text,uuid),public.create_tax_rate(uuid,text,text,numeric,public.tax_treatment,boolean,boolean) to authenticated;
