import Link from "next/link";
import type { TodayData } from "@/lib/today/data";
import styles from "./today.module.css";
const money=(value:number,currency:string)=>new Intl.NumberFormat("en-AE",{style:"currency",currency,minimumFractionDigits:Number.isInteger(value)?0:2,maximumFractionDigits:2}).format(value);
export function TodayView({data}:{data:TodayData}){const m=(v:number)=>money(v,data.currency),hour=Number(new Intl.DateTimeFormat("en-GB",{hour:"numeric",hour12:false,timeZone:data.timezone}).format(new Date())),displayName=/@|(?:-[a-z0-9]+){3,}/i.test(data.name)?"there":data.name;return <div className={styles.page}>
 <header className={styles.header}><div><h1>Good {hour<12?"morning":hour<17?"afternoon":"evening"}, {displayName}</h1><p>{data.status}</p></div><div className={styles.quickActions}><Link href="/sales/invoices/new">＋ Sale</Link><Link href="/purchases/bills/new">＋ Purchase</Link><Link href="/expenses/new">＋ Expense</Link><details><summary>Reports</summary><div><Link href="/reports/profit-loss">Profit &amp; Loss</Link><Link href="/reports/accounts-receivable">Receivables</Link><Link href="/reports/accounts-payable">Payables</Link><Link href="/reports/vat-summary">VAT</Link><Link href="/reports/stock-summary">Stock Summary</Link><Link href="/reports">View all reports</Link></div></details></div></header>
 {data.warnings.length>0&&<div className={styles.warning} role="status"><b>Some figures are unavailable.</b> {data.warnings.join(" ")}</div>}{!data.hasData&&data.warnings.length===0&&<div className={styles.empty}>Once you post an invoice, payment, bill, or expense, Home will highlight your financial position and next actions.</div>}
 <section className={styles.moneySection}><div className={styles.sectionHeading}><h2>Money now</h2><Link href="/overview" className={styles.back}>Dashboard ↗</Link></div>{data.money?<div className={styles.moneyGrid}><div className={styles.metric}><span>Cash now · cash &amp; bank</span><strong>{m(data.money.now)}</strong></div><div className={styles.metric}><span>Receivable · 7 days</span><strong>{m(data.money.coming)}</strong></div><div className={styles.metric}><span>Payable · 7 days</span><strong>{m(data.money.going)}</strong></div><div className={styles.metric}><span>Projected cash</span><strong>{m(data.money.projected)}</strong></div></div>:<p className={styles.unavailable}>Cash and due-date projection unavailable. Use the accounting reports for current balances.</p>}</section>
 <div className={styles.primaryGrid}><section className={styles.panel}><div className={styles.panelHead}><h2>Needs attention</h2><Link href="/reports/accounts-receivable">View all attention</Link></div>{data.attention===null?<p className={styles.unavailable}>Unable to verify open invoices and bills right now.</p>:data.attention.length===0?<div className={styles.allGood}><b>You&apos;re all caught up ✓</b>{data.nextCollections!==null&&data.nextCollections>0&&<small>{m(data.nextCollections)} is due from customers in the next seven days.</small>}</div>:<div className={styles.attentionRows}>{data.attention.slice(0,3).map(item=><Link href={item.href} key={item.id}><span><b>{item.title}</b><small>{item.detail}</small></span><strong>{m(item.amount)}</strong></Link>)}</div>}</section>
 <section className={styles.panel}><div className={styles.panelHead}><h2>Business today</h2><Link href="/overview">View activity</Link></div>{data.activity?<div className={styles.activityGrid}><div><span>Sales</span><b>{m(data.activity.invoiced)}</b></div><div><span>Received</span><b>{m(data.activity.received)}</b></div><div><span>Spent</span><b>{m(data.activity.spent)}</b></div></div>:<p className={styles.unavailable}>Same-day posted activity cannot be verified right now.</p>}</section></div>
 <section className={styles.upcoming}><b>{data.recommendation?"FYNTA recommends":"Upcoming"}</b><span>{data.recommendation?`Collect ${m(data.recommendation.amount)} from ${data.recommendation.title.split(" · ")[0]} today.`:data.upcoming?.[0]?`${data.upcoming[0].kind}: ${data.upcoming[0].party_name} · ${m(data.upcoming[0].outstanding)}`:"Nothing due in the next seven days."}</span>{data.recommendation?<Link href={data.recommendation.href}>Review invoice →</Link>:<Link href="/reports">View details</Link>}</section>
 <details className={styles.secondary}><summary>View business pulse details</summary><div>{data.pulse?<><p>Ledger revenue MTD <b>{m(data.pulse.revenue.current)}</b></p><p>Ledger costs &amp; expenses MTD <b>{m(data.pulse.expenses.current)}</b></p><p>Outstanding customer invoices <b>{data.pulse.outstanding===null?"—":m(data.pulse.outstanding)}</b></p></>:<p>Month-to-date ledger figures are unavailable.</p>}</div></details><span className="sr-only">Quick create</span>
 </div>}
